
development:
  adapter: postgresql
  encoding: unicode
  database: event_calendar_development
  pool: 5
  username: dev
  password: dev

test:
  adapter: postgresql
  encoding: unicode
  database: event_calendar_test
  pool: 5
  username: dev
  password: dev

production:
  adapter: postgresql
  encoding: unicode
  database: event_calendar_production
  pool: 5
  username: dev
  password: dev
